# Generated by Django 5.1.4 on 2025-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataset_is_public_dataset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='confidence_interval_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='confidence_interval_low',
            field=models.FloatField(default=0.0),
        ),
    ]
