# Generated by Django 5.1.4 on 2025-08-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='confidence',
        ),
    ]
