# Generated by Django 5.1.4 on 2025-08-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_question_difficulty_remove_question_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='explanation',
        ),
    ]
